### ISSUE TITLE
Don´t work with js.controller 1.4.2

### ISSUE THREAD

**Issue by BlueBook4** [Steiger04/ioBroker.milight-smart-light#12]
After Update js.controller:;

```
018-12-30 21:33:59.659 | error | instance system.adapter.milight-smart-light.0 terminated with code 0 (OK)
-- | -- | --
Caught | 2018-12-30 21:33:59.658 | error | by controller[0]: at Manager.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
Caught | 2018-12-30 21:33:59.658 | error | by controller[0]: at Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
Caught | 2018-12-30 21:33:59.658 | error | by controller[0]: at Socket.onpacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:244:12)
Caught | 2018-12-30 21:33:59.658 | error | by controller[0]: at Socket.onack (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:319:9)
Caught | 2018-12-30 21:33:59.658 | error | by controller[0]: at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:787:25)
Caught | 2018-12-30 21:33:59.658 | error | by controller[0]: at createInstancesObjects (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:748:13)
Caught | 2018-12-30 21:33:59.658 | error | by controller[0]: at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:788:29
Caught | 2018-12-30 21:33:59.658 | error | by controller[0]: at initAdapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:4990:18)
Caught | 2018-12-30 21:33:59.658 | error | by controller[0]: at Adapter.emit (events.js:185:7)
Caught | 2018-12-30 21:33:59.657 | error | by controller[0]: at emitNone (events.js:86:13)
Caught | 2018-12-30 21:33:59.657 | error | by controller[0]: at Adapter.adapter.on (/opt/iobroker/node_modules/iobroker.milight-smart-light/main.js:190:3)
Caught | 2018-12-30 21:33:59.657 | error | by controller[0]: at main (/opt/iobroker/node_modules/iobroker.milight-smart-light/main.js:197:21)
Caught | 2018-12-30 21:33:59.657 | error | by controller[0]: at Function.Promise.promisifyAll (/opt/iobroker/node_modules/iobroker.milight-smart-light/node_modules/bluebird/js/release/promisify.js:311:12)
Caught | 2018-12-30 21:33:59.657 | error | by controller[0]: at promisifyAll (/opt/iobroker/node_modules/iobroker.milight-smart-light/node_modules/bluebird/js/release/promisify.js:241:9)
Caught | 2018-12-30 21:33:59.657 | error | by controller[0]: at promisifiableMethods (/opt/iobroker/node_modules/iobroker.milight-smart-light/node_modules/bluebird/js/release/promisify.js:77:5)
Caught | 2018-12-30 21:33:59.657 | error | by controller[0]: at checkValid (/opt/iobroker/node_modules/iobroker.milight-smart-light/node_modules/bluebird/js/release/promisify.js:54:27)
Caught | 2018-12-30 21:33:59.657 | error | by controller[0]: See http://goo.gl/MqrFmX
Caught | 2018-12-30 21:33:59.656 | error | by controller[0]: TypeError: Cannot promisify an API that has normal methods with 'Async'-suffix
```

Please Help!!
It´s the only app with support for iBox

**Comment by gfxdude-dus** [comment]
did you fixed it?
