### ISSUE TITLE
Error after JS-Controller update

### ISSUE THREAD

**Issue by vr6syncro** [Steiger04/ioBroker.milight-smart-light#8]
```
milight-smart-light.0 | 2018-03-09 12:07:54.156 | error | at Manager.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
-- | -- | -- | --
milight-smart-light.0 | 2018-03-09 12:07:54.156 | error | at Manager. (/opt/iobroker/node_modules/component-bind/index.js:21:15)
milight-smart-light.0 | 2018-03-09 12:07:54.156 | error | at Socket.onpacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:236:12)
milight-smart-light.0 | 2018-03-09 12:07:54.156 | error | at Socket.onack (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:311:9)
milight-smart-light.0 | 2018-03-09 12:07:54.156 | error | at Socket. (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:786:25)
milight-smart-light.0 | 2018-03-09 12:07:54.156 | error | at createInstancesObjects (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:747:13)
milight-smart-light.0 | 2018-03-09 12:07:54.156 | error | at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:787:29
milight-smart-light.0 | 2018-03-09 12:07:54.156 | error | at initAdapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:4980:18)
milight-smart-light.0 | 2018-03-09 12:07:54.156 | error | at Adapter.emit (events.js:185:7)
milight-smart-light.0 | 2018-03-09 12:07:54.156 | error | at emitNone (events.js:86:13)
milight-smart-light.0 | 2018-03-09 12:07:54.156 | error | at Adapter.adapter.on (/opt/iobroker/node_modules/iobroker.milight-smart-light/main.js:190:3)
milight-smart-light.0 | 2018-03-09 12:07:54.156 | error | at main (/opt/iobroker/node_modules/iobroker.milight-smart-light/main.js:197:21)
milight-smart-light.0 | 2018-03-09 12:07:54.156 | error | at Function.Promise.promisifyAll (/opt/iobroker/node_modules/iobroker.milight-smart-light/node_modules/bluebird/js/release/promisify.js:311:12)
milight-smart-light.0 | 2018-03-09 12:07:54.156 | error | at promisifyAll (/opt/iobroker/node_modules/iobroker.milight-smart-light/node_modules/bluebird/js/release/promisify.js:241:9)
milight-smart-light.0 | 2018-03-09 12:07:54.156 | error | at promisifiableMethods (/opt/iobroker/node_modules/iobroker.milight-smart-light/node_modules/bluebird/js/release/promisify.js:77:5)
milight-smart-light.0 | 2018-03-09 12:07:54.156 | error | at checkValid (/opt/iobroker/node_modules/iobroker.milight-smart-light/node_modules/bluebird/js/release/promisify.js:54:27)
milight-smart-light.0 | 2018-03-09 12:07:54.156 | error | See http://goo.gl/MqrFmX
milight-smart-light.0 | 2018-03-09 12:07:54.156 | error | TypeError: Cannot promisify an API that has normal methods with 'Async'-suffix
milight-smart-light.0 | 2018-03-09 12:07:54.156 | error | See http://goo.gl/MqrFmX
milight-smart-light.0 | 2018-03-09 12:07:54.156 | error | uncaught exception: Cannot promisify an API that has normal methods with 'Async'-suffix
milight-smart-light.0 | 2018-03-09 12:07:54.148 | info | adapter:main->:::milight-smart-light::: wurde gestartet!
milight-smart-light.0 | 2018-03-09 12:07:54.143 | info | starting. Version 0.1.8 in /opt/iobroker/node_modules/iobroker.milight-smart-light, node: v6.13.1
milight-smart-light.0 | 2018-03-09 12:07:23.672 | info | terminating

```

**Comment by jasifa** [comment]
**I have the same problem after the update of:  iobroker.js-controller version 1.2.6
with version "1.2.7" too**


2018-03-08 00:17:53.524  - [32minfo[39m: milight-smart-light.0 States connected to redis: 127.0.0.1:6379
2018-03-08 00:17:53.777  - [32minfo[39m: milight-smart-light.0 starting. Version 0.1.8 in /opt/iobroker/node_modules/iobroker.milight-smart-light, node: v6.13.0
2018-03-08 00:17:53.824  - [32minfo[39m: milight-smart-light.0 adapter:main->:::milight-smart-light::: wurde gestartet!
2018-03-08 00:17:53.921  - [31merror[39m: milight-smart-light.0 uncaught exception: Cannot promisify an API that has normal methods with 'Async'-suffix
    See http://goo.gl/MqrFmX
2018-03-08 00:17:53.923  - [31merror[39m: milight-smart-light.0 TypeError: Cannot promisify an API that has normal methods with 'Async'-suffix
    See http://goo.gl/MqrFmX
    at checkValid (/opt/iobroker/node_modules/iobroker.milight-smart-light/node_modules/bluebird/js/release/promisify.js:54:27)
    at promisifiableMethods (/opt/iobroker/node_modules/iobroker.milight-smart-light/node_modules/bluebird/js/release/promisify.js:77:5)
    at promisifyAll (/opt/iobroker/node_modules/iobroker.milight-smart-light/node_modules/bluebird/js/release/promisify.js:241:9)
    at Function.Promise.promisifyAll (/opt/iobroker/node_modules/iobroker.milight-smart-light/node_modules/bluebird/js/release/promisify.js:311:12)
    at main (/opt/iobroker/node_modules/iobroker.milight-smart-light/main.js:197:21)
    at Adapter.adapter.on (/opt/iobroker/node_modules/iobroker.milight-smart-light/main.js:190:3)
    at emitNone (events.js:86:13)
    at Adapter.emit (events.js:185:7)
    at initAdapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:4955:18)
    at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:778:29
    at createInstancesObjects (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:747:13)
    at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:777:25)
    at Socket.onack (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:311:9)
    at Socket.onpacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:236:12)
    at Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
    at Manager.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)

**Comment by shrek1234** [comment]
**Same problem here after update to iobroker.js-controller version 1.2.6 with version "1.2.7"   >>> Cannot promisify an API that has normal methods with 'Async'-suffix**

2018-03-11 11:54:02.023 - debug: milight-smart-light.1 sendTo "deleteenums" to system.adapter.milight-smart-light.1 from system.adapter.milight-smart-light.1
2018-03-11 11:54:02.064 - silly: milight-smart-light.1 inMem message messagebox.system.adapter.milight-smart-light.1 messagebox.system.adapter.milight-smart-light.1 command=deleteenums, message=null, from=system.adapter.milight-smart-light.1, _id=39856606
2018-03-11 11:54:02.125 - error: Caught by controller[0]: TypeError: Cannot promisify an API that has normal methods with 'Async'-suffix
2018-03-11 11:54:02.125 - error: Caught by controller[0]: See http://goo.gl/MqrFmX
2018-03-11 11:54:02.125 - error: Caught by controller[0]: at checkValid (/opt/iobroker/node_modules/iobroker.milight-smart-light/node_modules/bluebird/js/release/promisify.js:54:27)
2018-03-11 11:54:02.125 - error: Caught by controller[0]: at promisifiableMethods (/opt/iobroker/node_modules/iobroker.milight-smart-light/node_modules/bluebird/js/release/promisify.js:77:5)
2018-03-11 11:54:02.126 - error: Caught by controller[0]: at promisifyAll (/opt/iobroker/node_modules/iobroker.milight-smart-light/node_modules/bluebird/js/release/promisify.js:241:9)
2018-03-11 11:54:02.126 - error: Caught by controller[0]: at Function.Promise.promisifyAll (/opt/iobroker/node_modules/iobroker.milight-smart-light/node_modules/bluebird/js/release/promisify.js:311:12)
2018-03-11 11:54:02.126 - error: Caught by controller[0]: at main (/opt/iobroker/node_modules/iobroker.milight-smart-light/main.js:197:21)
2018-03-11 11:54:02.127 - error: Caught by controller[0]: at Adapter.adapter.on (/opt/iobroker/node_modules/iobroker.milight-smart-light/main.js:190:3)
2018-03-11 11:54:02.127 - error: Caught by controller[0]: at emitNone (events.js:86:13)
2018-03-11 11:54:02.127 - error: Caught by controller[0]: at Adapter.emit (events.js:185:7)
2018-03-11 11:54:02.128 - error: Caught by controller[0]: at initAdapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:4980:18)
2018-03-11 11:54:02.128 - error: Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:787:29
2018-03-11 11:54:02.128 - error: Caught by controller[0]: at createInstancesObjects (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:747:13)
2018-03-11 11:54:02.128 - error: Caught by controller[0]: at Socket. (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:786:25)
2018-03-11 11:54:02.128 - error: Caught by controller[0]: at Socket.onack (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:311:9)
2018-03-11 11:54:02.128 - error: Caught by controller[0]: at Socket.onpacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:236:12)
2018-03-11 11:54:02.128 - error: Caught by controller[0]: at Manager. (/opt/iobroker/node_modules/component-bind/index.js:21:15)
2018-03-11 11:54:02.128 - error: Caught by controller[0]: at Manager.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
2018-03-11 11:54:02.128 - error: host.iobroker instance system.adapter.milight-smart-light.1 terminated with code 0 (OK)
2018-03-11 11:54:02.131 - info: host.iobroker Restart adapter system.adapter.milight-smart-light.1 because enabled
2018-03-11 11:54:21.304 - info: host.iobroker object change system.adapter.milight-smart-light.1
2018-03-11 11:54:33.031 - debug: milight-smart-light.1 objectDB connected
2018-03-11 11:54:33.079 - debug: milight-smart-light.1 statesDB connected
2018-03-11 11:54:33.181 - error: milight-smart-light.1 adapter disabled
2018-03-11 11:54:33.264 - error: host.iobroker instance system.adapter.milight-smart-light.1 terminated with code 3 (Adapter disabled or invalid config)
2018-03-11 11:54:33.265 - info: host.iobroker Do not restart adapter system.adapter.milight-smart-light.1 because disabled or deleted

**Comment by shrek1234** [comment]
Looks like there was a change in the ioBroker.js-controller by adding promisified methods, see changelog
[https://github.com/ioBroker/ioBroker.js-controller/blob/master/CHANGELOG.md#127-2018-03-06](url)
**(AlCalzone) Add promisified methods to the adapter class**

Unfortunatelly I am not a programming guy, so cannot go deeper into it. Guess the actual solution is going back to 1.2.6 and wait until the adapter will (can) be adjusted.

**Comment by shrek1234** [comment]
Looks like there was achnage in the io.Broker js-controller by adding promisified methods, see changelog
[https://github.com/ioBroker/ioBroker.js-controller/blob/master/CHANGELOG.md#127-2018-03-06](url)

(AlCalzone) Add promisified methods to the adapter class

**Comment by shrek1234** [comment]
Looks like there was a change in the ioBroker.js-controller by adding promisified methods, see changelog
https://github.com/ioBroker/ioBroker.js-controller/blob/master/CHANGELOG.md#127-2018-03-06

**(AlCalzone) Add promisified methods to the adapter class**

Unfortunatelly I am not a programming guy, so cannot go deeper into it. Guess the actual solution is going back to 1.2.6 and wait until the adapter will (can) be adjusted.

**Comment by Steiger04** [comment]
I fixed the bug. Please use the new version 0.1.9 and install it via iobroker.admin github. The npm version will follow later.

**Comment by shrek1234** [comment]
Works fine again, thanks for prompt fixing the problem.
